services:
  personalfinancemanager.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/PersonalFinanceManager.API.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=personalfinancemanagerkey
    ports:
      - "3565:8080"
      - "3566:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro